locale: "sv"
site_url: https://dannesteknikhorna.se
localbackend: true
backend:
  name: git-gateway
  repo: Danster2020/Dannes_Teknikhorna
  branch: master

media_folder: src/blog/images
# public_folder: /uploads

collections:
  - label: "Projekt"
    name: "blog_posts"
    folder: "src/blog"
    create: true
    fields:
      - {
          name: "slug",
          label: "Path",
          widget: "string",
          hint: "sökvägen som visas i URL:en. T.ex /hem",
          pattern:
            [
              "^[A-Za-z0-9_-]*$",
              "Får endast innehålla bokstäver eller siffror",
            ],
          required: true,
        }
      - {
          name: "title",
          label: "Titel",
          widget: "string",
          hint: "Titel som visas på sidan",
          required: true,
        }
      - {
          name: "description",
          label: "Beskrivning",
          widget: "string",
          hint: "Kort text om projektet.",
          required: true,
        }
      - { name: "image", label: "Bild", widget: "image", required: true }
      - {
          name: "featured",
          label: "Featured",
          widget: "select",
          options: [-1, 0, 1, 2],
          default: -1,
          hint: "Ordning på indexsidan. '-1': ej featured.",
        }
      - { name: "published", label: "Publiserad", widget: "datetime" }
